;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/YAML/main/Direct.list
ruleset=HK,https://raw.githubusercontent.com/samkolau/YAML/main/HK.list
ruleset=JP,https://raw.githubusercontent.com/samkolau/YAML/main/JP.list
ruleset=KR,https://raw.githubusercontent.com/samkolau/YAML/main/KR.list
ruleset=MO,https://raw.githubusercontent.com/samkolau/YAML/main/MO.list
ruleset=SG,https://raw.githubusercontent.com/samkolau/YAML/main/SG.list
ruleset=MY,https://raw.githubusercontent.com/samkolau/YAML/main/MY.list
ruleset=IN,https://raw.githubusercontent.com/samkolau/YAML/main/IN.list
ruleset=US,https://raw.githubusercontent.com/samkolau/YAML/main/US.list
ruleset=TW,https://raw.githubusercontent.com/samkolau/YAML/main/TW.list
ruleset=CA,https://raw.githubusercontent.com/samkolau/YAML/main/CA.list
ruleset=RU,https://raw.githubusercontent.com/samkolau/YAML/main/RU.list
ruleset=DE,https://raw.githubusercontent.com/samkolau/YAML/main/DE.list
ruleset=NZ,https://raw.githubusercontent.com/samkolau/YAML/main/NZ.list
ruleset=ES,https://raw.githubusercontent.com/samkolau/YAML/main/ES.list
ruleset=TH,https://raw.githubusercontent.com/samkolau/YAML/main/TH.list
ruleset=TR,https://raw.githubusercontent.com/samkolau/YAML/main/TR.list
ruleset=VN,https://raw.githubusercontent.com/samkolau/YAML/main/VN.list
ruleset=FR,https://raw.githubusercontent.com/samkolau/YAML/main/FR.list
ruleset=MX,https://raw.githubusercontent.com/samkolau/YAML/main/MX.list
ruleset=IT,https://raw.githubusercontent.com/samkolau/YAML/main/IT.list
ruleset=MM,https://raw.githubusercontent.com/samkolau/YAML/main/MM.list
ruleset=NP,https://raw.githubusercontent.com/samkolau/YAML/main/NP.list
ruleset=DIRECT,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Unbreak.list
#ruleset=REJECT,https://raw.githubusercontent.com/samkolau/YAML/main/Advertising.list
#ruleset=Netflix,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Netflix.list
#ruleset=Disney,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/StreamingMedia/Video/DisneyPlus.list
#ruleset=Streaming,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list
#ruleset=StreamingSE,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list
#ruleset=Apple,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/Extra/Apple/Apple.list
#ruleset=Proxies,https://raw.githubusercontent.com/samkolau/YAML/main/Global.list
ruleset=DIRECT,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/China.list
ruleset=DIRECT,https://raw.githubusercontent.com/AGWA5783/Profiles/master/Surge/Ruleset/LocalAreaNetwork.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=Proxies,[]MATCH
;设置规则标志位

;设置分组标志位
custom_proxy_group=Proxies`select`[]HK`[]JP`[]SG`[]TW`[]US`[]IN`.*
custom_proxy_group=Netflix`select`[]Proxies`[]HK`[]JP`[]SG`[]TW`[]US`NF|Netflix|NETFLIX|原生|解锁
custom_proxy_group=Disney`select`[]Proxies`[]HK`[]JP`[]SG`[]TW`[]US
custom_proxy_group=Streaming`select`[]Proxies`[]HK`[]JP`[]SG`[]TW`[]US
custom_proxy_group=StreamingSE`select`[]DIRECT`[]HK`[]TW
custom_proxy_group=Apple`select`[]Proxies`[]DIRECT`[]HK`[]JP`[]US
custom_proxy_group=IN`select`印度|IN|India|印度
custom_proxy_group=CA`select`加拿大|CA|Canada|加拿大
custom_proxy_group=RU`select`俄国|俄國|RU|Russia|俄罗斯|俄羅斯
custom_proxy_group=DE`select`德国|德國|DE|Germany
custom_proxy_group=NZ`select`新西兰|新西蘭|NZ|Newzealand|New Zealand
custom_proxy_group=ES`select`西班牙|ES|Spain|西班牙
custom_proxy_group=TH`select`TH|泰国|泰國|Thailand
custom_proxy_group=TR`select`TR|土耳其|Türkiye|Turkey|土耳其
custom_proxy_group=VN`select`VN|越南|Vietnam|Viet
custom_proxy_group=FR`select`FR|法国|法國|France
custom_proxy_group=MX`select`MX|墨西哥|Mexico
custom_proxy_group=IT`select`IT|意大利|Italy|義大利
custom_proxy_group=HK`select`香港|HK|Hong Kong
custom_proxy_group=MO`select`澳门|澳門|MO|Macao
custom_proxy_group=MM`select`缅甸|MM|Myanmar|緬甸
custom_proxy_group=NP`select`尼泊尔|NP|Nepal|尼泊爾
custom_proxy_group=MY`select`马来西亚|大马|MY|Malaysia|馬來西亞|大馬
custom_proxy_group=SG`select`新加坡|狮城|SG|Singapore
custom_proxy_group=TW`select`台湾|台灣|新北|彰化|TW|Taiwan
custom_proxy_group=JP`select`日本|东京|大阪|埼玉|JP|Japan
custom_proxy_group=KR`select`韩国|首尔|釜山|KR|Korea|korea
custom_proxy_group=US`select`美国|美國|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|America|USA
;设置分组标志位
